/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imagenes;

import static imagenes.ImgPrincipal114.MI1;
import static imagenes.ImgPrincipal114.aristaPixel;
import static imagenes.ImgPrincipal114.grafClase;
import static imagenes.ImgPrincipal114.jLabel21;
import static imagenes.ImgPrincipal114.listas;
import static imagenes.ImgPrincipal114.totClas;
//import static imagenes.ImgPrincipal114.txtAristaPixel;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author gabest
 */
public class jDialogPixelar extends javax.swing.JDialog {

    /**
     * Creates new form jDialogPixelar
     */
    public jDialogPixelar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jDialogPixelar.txtClaseNumero.setText(String.valueOf(0));
        jDialogPixelar.txtArista.setText(String.valueOf(1));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPixelar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnDlgResetOriginal = new javax.swing.JButton();
        btnDlVerPixelado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtArista = new javax.swing.JTextField();
        txtCantidadClases = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtClaseNumero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTamañoClase = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtRed = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtGreen = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtBlue = new javax.swing.JTextField();
        btnVerClase = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnDlgResetOriginal1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        btnPixelar.setText("Pixelar");
        btnPixelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPixelarActionPerformed(evt);
            }
        });

        jButton3.setText("Ver Original");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnDlgResetOriginal.setText("Reset Original");
        btnDlgResetOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgResetOriginalActionPerformed(evt);
            }
        });

        btnDlVerPixelado.setText("Ver Pixelado");
        btnDlVerPixelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlVerPixeladoActionPerformed(evt);
            }
        });

        jLabel1.setText("Arista del pixel");

        jLabel2.setText("Cantidad de clases");

        txtArista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAristaActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtClaseNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaseNumeroActionPerformed(evt);
            }
        });

        jLabel3.setText("Tamaño");

        jLabel4.setText("Clase n°");

        jLabel5.setText("Color");

        jLabel6.setText("R");

        jLabel7.setText("G");

        jLabel8.setText("B");

        btnVerClase.setBackground(new java.awt.Color(0, 204, 255));
        btnVerClase.setText("Ver Clase");
        btnVerClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerClaseActionPerformed(evt);
            }
        });

        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnAnterior)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(14, 14, 14)
                        .addComponent(txtClaseNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSiguiente))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtRed, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTamañoClase, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnVerClase)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClaseNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnAnterior)
                    .addComponent(btnSiguiente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerClase)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTamañoClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        btnDlgResetOriginal1.setText("Reset Anterior");
        btnDlgResetOriginal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDlgResetOriginal1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDlVerPixelado, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPixelar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtArista, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDlgResetOriginal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(51, 51, 51)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtCantidadClases, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDlgResetOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtArista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPixelar)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDlVerPixelado)
                    .addComponent(btnDlgResetOriginal1)
                    .addComponent(txtCantidadClases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(btnDlgResetOriginal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPixelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPixelarActionPerformed
        // TODO add your handling code here:
        
        aristaPixel= Integer.valueOf(txtArista.getText());
        ImgPrincipal114.miPixelarAux();
        txtCantidadClases.setText(String.valueOf(ImgPrincipal114.listas.size()));
        
    }//GEN-LAST:event_btnPixelarActionPerformed

    private void btnDlVerPixeladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlVerPixeladoActionPerformed
        // TODO add your handling code here:
        
        MI1 = new ImageIcon(ImgPrincipal114.archivosPath);
        ImgPrincipal114.img1 = MI1.getImage();
        ImgPrincipal114.newImg1 = ImgPrincipal114.img1.getScaledInstance((int)ImgPrincipal114.and, (int)ImgPrincipal114.ald, Image.SCALE_DEFAULT);
        ImgPrincipal114.image1 = new ImageIcon(ImgPrincipal114.newImg1);           
        ImgPrincipal114.jLabel21.setIcon(ImgPrincipal114.image1);
        
    }//GEN-LAST:event_btnDlVerPixeladoActionPerformed

    private void btnDlgResetOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgResetOriginalActionPerformed
        // TODO add your handling code here:
        ImgPrincipal114.miaResetearOriginal();
        
    }//GEN-LAST:event_btnDlgResetOriginalActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(ImgPrincipal114.image);
        
    }//GEN-LAST:event_jButton3ActionPerformed
    
    static int Cr, Cg, Cb, color, orden, grafClase;
    
    private void btnVerClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerClaseActionPerformed
        // TODO add your handling code here:
        
        verClaseActiva();
        
    }
    
    private void verClaseActiva() {
          
        grafClase= Integer.valueOf(this.txtClaseNumero.getText());

        Cr=(int)listas.get(grafClase).cR;
        Cg=(int)listas.get(grafClase).cG;
        Cb=(int)listas.get(grafClase).cB;
        color= new Color(Cr, Cg, Cb).getRGB();
        //color= listas.get(grafClase).colorClase.;
        // orden de la clase (lo saco de la lista ordenada)
        //orden= listaOrdenada.get(grafClase).valor;
        orden= listas.get(grafClase).listaV.size();
        this.txtColor.setText(String.valueOf(color));
        this.txtTamañoClase.setText(String.valueOf(orden));

        //int red = new Color(color).getRed();

        this.txtRed.setText(String.valueOf(new Color(color).getRed()));
        this.txtGreen.setText(String.valueOf(new Color(color).getGreen()));
        this.txtBlue.setText(String.valueOf(new Color(color).getBlue()));
       
        ImgPrincipal114.presentarClaseColor(grafClase, orden, listas);
        
    }//GEN-LAST:event_btnVerClaseActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        grafClase= Integer.valueOf(this.txtClaseNumero.getText());
        if (grafClase>0)
        {
            grafClase=grafClase-1;
            txtClaseNumero.setText(String.valueOf(grafClase));            
        }
        this.verClaseActiva();     
        
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        grafClase= Integer.valueOf(this.txtClaseNumero.getText());
        totClas= Integer.valueOf(this.txtCantidadClases.getText());
        if (grafClase<totClas-1)
        {
            grafClase=grafClase+1;
            txtClaseNumero.setText(String.valueOf(grafClase));            
        }
        this.verClaseActiva();     
        
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void txtAristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAristaActionPerformed

    private void txtClaseNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaseNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaseNumeroActionPerformed

    private void btnDlgResetOriginal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDlgResetOriginal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDlgResetOriginal1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jDialogPixelar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jDialogPixelar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jDialogPixelar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jDialogPixelar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jDialogPixelar dialog = new jDialogPixelar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnDlVerPixelado;
    private javax.swing.JButton btnDlgResetOriginal;
    private javax.swing.JButton btnDlgResetOriginal1;
    private javax.swing.JButton btnPixelar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnVerClase;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JTextField txtArista;
    public static javax.swing.JTextField txtBlue;
    private javax.swing.JTextField txtCantidadClases;
    public static javax.swing.JTextField txtClaseNumero;
    private javax.swing.JTextField txtColor;
    public static javax.swing.JTextField txtGreen;
    public static javax.swing.JTextField txtRed;
    private javax.swing.JTextField txtTamañoClase;
    // End of variables declaration//GEN-END:variables
}
