/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imagenes;

import static imagenes.ImgPrincipal114.MI1;
import static imagenes.ImgPrincipal114.aristaPixel;
import static imagenes.jDialogPixelar.txtArista;
import java.awt.Image;
import javax.swing.ImageIcon;


/**
 *
 * @author gabest
 */
public class JDialogSectorizar extends javax.swing.JDialog {

    /**
     * Creates new form JDialogSectorizar
     */
    public JDialogSectorizar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    // inicializar txtAristaDesdeSect     
        JDialogSectorizar.txtAristaDesdeSect.setText(String.valueOf(121));
        JDialogSectorizar.txtFiltroContorno.setText(String.valueOf(50));
    // inicializar txtColorActivo y sector
    //    JDialogSectorizar.txtColorActivo.setText(String.valueOf(0));
    //    JDialogSectorizar.txtSectorActivo.setText(String.valueOf(0));
                  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSectorizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCantidadDeColores = new javax.swing.JTextField();
        btnPixelarDesdeSect = new javax.swing.JButton();
        txtAristaDesdeSect = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTiempoSectorizado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnVerContornos = new javax.swing.JButton();
        txtFiltroContorno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnVerContorno = new javax.swing.JButton();
        txtColorActivo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCantSectores = new javax.swing.JTextField();
        txtSectorActivo = new javax.swing.JTextField();
        btnSigColor = new javax.swing.JButton();
        btnAntColor = new javax.swing.JButton();
        btnAntSector = new javax.swing.JButton();
        btnSigSector = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnVerSectores = new javax.swing.JButton();
        btnAntContorno1 = new javax.swing.JButton();
        txtContornoActivo1 = new javax.swing.JTextField();
        btnSigContorno1 = new javax.swing.JButton();
        btnVerSector1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        btnSectorizar.setText("Sectorizar");
        btnSectorizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSectorizarActionPerformed(evt);
            }
        });

        jLabel2.setText("Cantidad de colores");

        btnPixelarDesdeSect.setText("Pixelar");
        btnPixelarDesdeSect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPixelarDesdeSectActionPerformed(evt);
            }
        });

        txtAristaDesdeSect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAristaDesdeSectActionPerformed(evt);
            }
        });

        jLabel5.setText("Arista");

        jLabel6.setText("Tiempo");

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnVerContornos.setText("Contornos");
        btnVerContornos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerContornosActionPerformed(evt);
            }
        });

        jLabel7.setText("% filtrado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSectorizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPixelarDesdeSect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidadDeColores, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnVerContornos)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnReset)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(txtTiempoSectorizado, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFiltroContorno, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAristaDesdeSect, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSectorizar)
                    .addComponent(jLabel2)
                    .addComponent(txtCantidadDeColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPixelarDesdeSect)
                        .addComponent(btnReset))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTiempoSectorizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAristaDesdeSect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVerContornos)
                            .addComponent(txtFiltroContorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addContainerGap())))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("SECTORIZACIÓN");

        jButton1.setText("Salir");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        btnVerContorno.setText("ver Contorno");
        btnVerContorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerContornoActionPerformed(evt);
            }
        });

        jLabel4.setText("Cantidad de sectores");

        btnSigColor.setText("Siguiente");
        btnSigColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigColorActionPerformed(evt);
            }
        });

        btnAntColor.setText("Anterior");
        btnAntColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntColorActionPerformed(evt);
            }
        });

        btnAntSector.setText("Anterior");
        btnAntSector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntSectorActionPerformed(evt);
            }
        });

        btnSigSector.setText("Siguiente");
        btnSigSector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigSectorActionPerformed(evt);
            }
        });

        jLabel3.setText("Color");

        btnVerSectores.setText("Ver SECTORES");
        btnVerSectores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSectoresActionPerformed(evt);
            }
        });

        btnAntContorno1.setText("Anterior");
        btnAntContorno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntContorno1ActionPerformed(evt);
            }
        });

        btnSigContorno1.setText("Siguiente");
        btnSigContorno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigContorno1ActionPerformed(evt);
            }
        });

        btnVerSector1.setText("Ver Sector");
        btnVerSector1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSector1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAntColor)
                .addGap(18, 18, 18)
                .addComponent(txtColorActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSigColor))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtCantSectores, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVerSectores)
                .addGap(39, 39, 39))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAntSector)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSectorActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSigSector))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVerContorno)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnAntContorno1)
                                .addGap(18, 18, 18)
                                .addComponent(txtContornoActivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnSigContorno1)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(btnVerSector1)
                    .addContainerGap(191, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtColorActivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAntColor)
                    .addComponent(btnSigColor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtCantSectores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerSectores, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSectorActivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSigSector)
                    .addComponent(btnAntSector))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerContorno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContornoActivo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAntContorno1)
                    .addComponent(btnSigContorno1))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addComponent(btnVerSector1)
                    .addContainerGap(102, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSectorizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSectorizarActionPerformed
        // TODO add your handling code here:
        
        ImgPrincipal114.miSectorizarAux ();
        
        // tiempo de sectorizado
        txtTiempoSectorizado.setText(String.valueOf(ImgPrincipal114.tiempo));
        
        // completar cantidad de colores
        txtCantidadDeColores.setText(String.valueOf(ImgPrincipal114.listasS.size()));
        // establecer com clase inicial la cero
        txtColorActivo.setText(String.valueOf(0));
        // anotar su cantidad de sectores
        txtCantSectores.setText(String.valueOf(ImgPrincipal114.listasS.get(0).Sectores.size()));
        // anotar como cero el sector inicial
        txtSectorActivo.setText(String.valueOf(0));
        
    }//GEN-LAST:event_btnSectorizarActionPerformed

    private void btnPixelarDesdeSectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPixelarDesdeSectActionPerformed
        // TODO add your handling code here:
        
        aristaPixel= Integer.valueOf(txtAristaDesdeSect.getText());
        ImgPrincipal114.miPixelarAux();
        txtCantidadDeColores.setText(String.valueOf(ImgPrincipal114.listas.size()));
        
        MI1 = new ImageIcon(ImgPrincipal114.archivosPath);
        ImgPrincipal114.img1 = MI1.getImage();
        ImgPrincipal114.newImg1 = ImgPrincipal114.img1.getScaledInstance((int)ImgPrincipal114.and, (int)ImgPrincipal114.ald, Image.SCALE_DEFAULT);
        ImgPrincipal114.image1 = new ImageIcon(ImgPrincipal114.newImg1);           
        ImgPrincipal114.jLabel21.setIcon(ImgPrincipal114.image1);
        // establecer com clase inicial la cero
        txtColorActivo.setText(String.valueOf(0));
        // anotar como cero el sector inicial
        txtSectorActivo.setText(String.valueOf(0));
    }//GEN-LAST:event_btnPixelarDesdeSectActionPerformed

    
    static int ColorActivo, SectorActivo;
    
    private void btnVerContornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerContornoActionPerformed
        // TODO add your handling code here:
        
        // leer conjunto y sector activos
        ColorActivo= Integer.valueOf(this.txtColorActivo.getText());
        SectorActivo= Integer.valueOf(this.txtSectorActivo.getText());
        
        // llamar al método de ImgPpal que muestra el sector
        ImgPrincipal114.presentarCtoColorSector( ColorActivo, SectorActivo );
        
    }//GEN-LAST:event_btnVerContornoActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        
        ImgPrincipal114.miaResetearOriginal();
        
    }//GEN-LAST:event_btnResetActionPerformed

    public static int sectAct, colAct, totSecColAct, totColores;
    
    private void btnSigSectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigSectorActionPerformed
        // TODO add your handling code here:
        
        // leer sector actual
        ColorActivo= Integer.valueOf(this.txtColorActivo.getText());
        SectorActivo= Integer.valueOf(this.txtSectorActivo.getText());
        
        // determinar cantidad de sectores del color actual
        totSecColAct= ImgPrincipal114.listasS.get(ColorActivo).Sectores.size();
        
        // if sector actual + 1 < total
        if( SectorActivo+1 < totSecColAct )
        {//      ->  sector actual + 1
            SectorActivo= SectorActivo + 1;
            txtSectorActivo.setText(String.valueOf(SectorActivo));
            //      mostrar sector actual
            ImgPrincipal114.presentarCtoColorSector( ColorActivo, SectorActivo ); 
        }
        
        
    }//GEN-LAST:event_btnSigSectorActionPerformed

    private void btnAntSectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntSectorActionPerformed
        // TODO add your handling code here:
        
         // leer sector actual
        ColorActivo= Integer.valueOf(this.txtColorActivo.getText());
        SectorActivo= Integer.valueOf(this.txtSectorActivo.getText());
        
        // determinar cantidad de sectores del color actual
        totSecColAct= ImgPrincipal114.listasS.get(ColorActivo).Sectores.get(SectorActivo).VerticesDelSr.size();
        
        // if sector actual + 1 < total
        if( SectorActivo > 0 )
        {//      ->  sector actual + 1
            SectorActivo= SectorActivo - 1;
            txtSectorActivo.setText(String.valueOf(SectorActivo));
            //      mostrar sector actual
            ImgPrincipal114.presentarCtoColorSector( ColorActivo, SectorActivo ); 
        }
    }//GEN-LAST:event_btnAntSectorActionPerformed

    private void btnAntColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntColorActionPerformed
        // TODO add your handling code here:
                
        // leer color actual
        ColorActivo= Integer.valueOf(this.txtColorActivo.getText());
        
        // if sector actual + 1 < total
        if( ColorActivo > 0 )
        {//      ->  sector actual + 1
            ColorActivo= ColorActivo - 1;
            txtColorActivo.setText(String.valueOf(ColorActivo));
            txtSectorActivo.setText(String.valueOf(0));
            SectorActivo= 0;
            // anotar su cantidad de sectores
            txtCantSectores.setText(String.valueOf(ImgPrincipal114.listasS.get(ColorActivo).Sectores.size()));
            // mostrar sector actual
            ImgPrincipal114.presentarCtoColor(ColorActivo);
            //ImgPrincipal.presentarCtoColorSector( ColorActivo, SectorActivo ); 
        }
    }//GEN-LAST:event_btnAntColorActionPerformed

    private void btnSigColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigColorActionPerformed
        // TODO add your handling code here:
            // leer sector actual
   
        ColorActivo= Integer.valueOf(this.txtColorActivo.getText());
        SectorActivo= Integer.valueOf(this.txtSectorActivo.getText());
        
        // determinar cantidad de sectores del color actual
        totColores= ImgPrincipal114.listasS.size();
        
        // if sector actual + 1 < total
        if( ColorActivo+1 < totColores )
        {//      ->  sector actual + 1
            ColorActivo= ColorActivo + 1;
            txtColorActivo.setText(String.valueOf(ColorActivo));
            txtSectorActivo.setText(String.valueOf(0));
            SectorActivo= 0;
            // anotar su cantidad de sectores
            txtCantSectores.setText(String.valueOf(ImgPrincipal114.listasS.get(ColorActivo).Sectores.size()));
            //      mostrar sector actual
            ImgPrincipal114.presentarCtoColor(ColorActivo);
            //ImgPrincipal.presentarCtoColorSector( ColorActivo, SectorActivo ); 
        }
        
    
        
    }//GEN-LAST:event_btnSigColorActionPerformed
    
    public static int is, ts;
    private void btnVerSectoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSectoresActionPerformed
        // TODO add your handling code here:
        
        // leer conjunto y sector activos
        ColorActivo= Integer.valueOf(this.txtColorActivo.getText());
        //SectorActivo= Integer.valueOf(this.txtSectorActivo.getText());
        ImgPrincipal114.presentarCtoColor(ColorActivo);
        
        
    }//GEN-LAST:event_btnVerSectoresActionPerformed

    private void btnAntContorno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntContorno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAntContorno1ActionPerformed

    private void btnSigContorno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigContorno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSigContorno1ActionPerformed

    private void btnVerSector1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSector1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerSector1ActionPerformed

    private void btnVerContornosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerContornosActionPerformed
        // TODO add your handling code here:
        ImgPrincipal114.filtroC= Float.valueOf(this.txtFiltroContorno.getText());;
        ImgPrincipal114.miVerContornos();
        
    }//GEN-LAST:event_btnVerContornosActionPerformed

    private void txtAristaDesdeSectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAristaDesdeSectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAristaDesdeSectActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogSectorizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogSectorizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogSectorizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogSectorizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogSectorizar dialog = new JDialogSectorizar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAntColor;
    private javax.swing.JButton btnAntContorno1;
    private javax.swing.JButton btnAntSector;
    private javax.swing.JButton btnPixelarDesdeSect;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSectorizar;
    private javax.swing.JButton btnSigColor;
    private javax.swing.JButton btnSigContorno1;
    private javax.swing.JButton btnSigSector;
    private javax.swing.JButton btnVerContorno;
    private javax.swing.JButton btnVerContornos;
    private javax.swing.JButton btnVerSector1;
    private javax.swing.JButton btnVerSectores;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private static javax.swing.JTextField txtAristaDesdeSect;
    private javax.swing.JTextField txtCantSectores;
    private javax.swing.JTextField txtCantidadDeColores;
    private static javax.swing.JTextField txtColorActivo;
    private static javax.swing.JTextField txtContornoActivo1;
    public static javax.swing.JTextField txtFiltroContorno;
    private static javax.swing.JTextField txtSectorActivo;
    private javax.swing.JTextField txtTiempoSectorizado;
    // End of variables declaration//GEN-END:variables
}
